server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blps
    username: postgres
    password: DenDenvv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect